resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/integration-service/config/default?ref=df946d0d3977ab37e9010d778640c85e8e8cdb94
- .tekton/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: df946d0d3977ab37e9010d778640c85e8e8cdb94

namespace: integration-service

patches:
  - ./manager_resources_patch.yaml
